version: "2.4"

services:
  backend:
    build: .
    container_name: backend
    environment:
      - "TZ=${TIMEZONE}"
      - "ADMIN_USERNAME=${ADMIN_USERNAME}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "DATABASE_URL=postgres://bjoetiek:bjoetiek@db/bjoetiek"
      - "RUST_LOG=debug"
    networks:
      - bjoetiek
    ports:
      - "127.0.0.1:8090:8090"

  db:
    image: postgres:13-alpine
    container_name: bjoetiek-db
    environment:
      - "TZ=${TIMEZONE}"
      - "POSTGRES_USER=bjoetiek"
      - "POSTGRES_PASSWORD=bjoetiek"
    networks:
      - bjoetiek
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - bjoetiek
    ports:
      - "127.0.0.1:8032:80"
    volumes:
      - "bjoetiek-pgadmin:/var/lib/pgadmin"
    environment:
      - "TZ=${TIMEZONE}"
      - "PGADMIN_DEFAULT_EMAIL=admin@bjoetiek-y.be"
      - "PGADMIN_DEFAULT_PASSWORD=bjoetiek"

networks:
  bjoetiek:
    name: bjoetiek

volumes:
  bjoetiek-pgadmin:
