version: "3.8"

services:
  bjoetiek-backend:
    build: .
    container_name: bjoetiek-backend
    environment:
      - "TZ=${TIMEZONE}"
      - "DATABASE_URL=${DATABASE_URL}"
    ports:
      - "127.0.0.1:8090:8090"

  bjoetiek-db:
    image: postgres:13-alpine
    container_name: bjoetiek-db
    environment:
      - "TZ=${TIMEZONE}"
      - "POSTGRES_USER=bjoetiek"
      - "POSTGRES_PASSWORD=bjoetiek"
    ports:
      - "127.0.0.1:5432:5432"
