name: Test, build and publish
on:
  push:
    branches: [main]

env:
  DOCKER_HUB_USER: jenswbebot
  DOCKER_HUB_REPO: jenswbe/bjoetiek-y-backend
  PLATFORMS: linux/amd64,linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:latest

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPO }}
